<!DOCTYPE html>
 <html lang="en">
 <head>
 	<meta charset="UTF-8">
 	<title>Document</title>
 </head>
 <body>
 	<script>
 		// 用new Promise 实例化的promise对象有以下三个状态

		// resolve(成功)时。此时会调用 onFulfilled

		// reject(失败)时。此时会调用 onRejected

		// Pending 既不是resolve也不是reject的状态。也就是promise对象刚被创建后的初始化状态等

		function getURL(URL) {
		    return new Promise(function (resolve, reject) {
		        var req = new XMLHttpRequest();
		        req.open('GET', URL, true);
		        req.onload = function () {
		            if (req.status === 200) {
		                resolve(req.responseText);
		            } else {
		                reject(new Error(req.statusText));
		            }
		        };
		        req.onerror = function () {
		            reject(new Error(req.statusText));
		        };
		        req.send();
		    });
		}

		// 运行示例
		var URL = "http://httpbin.org/get";
		//var URL = "http://httpbin.org/status/500";
		getURL(URL).then(function onFulfilled(value){
		    console.log(value);
		}).catch(function onRejected(error){
		    console.error(error);
		});


 	</script>
 </body>
 </html> 